name: Validate slides markdown
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  markdown-lint:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Run markdown linter
        run: npx markdownlint-cli2 .
  spell-check:
    name: Run spell checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Run spell checker
        run: npx cspell .
